Esp32 sleep
Hounsvad/ScalableTeaching-IOT pull request #12
Opened 2023-01-24 11:54 UTC by Zheraan

Added the guide for sleep modes with a simple code example and a link to a more detailed use, as well as links to the relevant API reference parts.

Closes #11

2023-01-25 16:35 UTC, Hounsvad requested changes

2023-01-25 16:35 UTC, Hounsvad commented on guides/esp32-sleep-modes.md
> +- ULP coprocessor
Describe what these things do

2023-01-25 16:35 UTC, Hounsvad commented on guides/esp32-sleep-modes.md
> +		// This prevents rounding errors, especially when dealing with shorter times
How on earth would a "rounding" error occur on an integer. Do you mean overflow. If there is some other thing that happens behind the scene then please explain that.

2023-01-25 16:35 UTC, Hounsvad commented on guides/esp32-sleep-modes.md
> +
It would be good to have an example wake on an interrupt

2023-01-31 18:59 UTC, Zheraan commented on guides/esp32-sleep-modes.md
> +		// This prevents rounding errors, especially when dealing with shorter times
I meant to use a _double_ for the time_in_sec variable instead of an _int_. Most C compilers should convert to the largest (bit-width wise) type used between the two, but from what I read funny things can happen with some special compilers that try to optimize it for Microcontrollers. So I put this so they don't get screwed if they copy this code snippet and use it in a different environment. From what I gather, ESP-IDF uses GCC on Linux and on Windows different cross-compilers are used, and since GCC is heavily customisable I preferred to include this inconsequential detail to make sure there are no weird issues on either operating systems.

2023-01-31 19:00 UTC, Zheraan commented on guides/esp32-sleep-modes.md
> +- ULP coprocessor
I added hyperlinks to the info on Espressif's website

2023-01-31 19:17 UTC, Zheraan commented on guides/esp32-sleep-modes.md
> +		// This prevents rounding errors, especially when dealing with shorter times
Also this provides higher precision when multiplying it with a _float_, because when the multiplication is processed, the _integer_ would be "promoted" to a _float_, providing less precision than if we specify it as a _long long_. In this case, the other operand is promoted to this long double format as well when the result is calculated, resulting in higher precision since the result is then implicitly converted to an int since that's what esp_deep_sleep is using. That's inconsequential most of the time, but when dealing with decimals with different resolutions and precise timings (for example the ~μs precision of the High Resolution Timer), it can matter. 

Overall, it's just best practice to do so, and you are right that it actually doesn't matter if we're multiplying an int with an int, that's a mistake on my part, I wanted to use doubles but the ESP example I took inspiration from used integers so I didn't think twice.

2023-01-31 19:27 UTC, Zheraan commented on guides/esp32-sleep-modes.md
> +
Examples vary depending on the wakeup source, I'll tell them to refer to the documentation for an use-case specific solution, in case they need this. I don't have the time to write an example for one of the specific methods

2023-01-31 20:25 UTC, merged